=== ZugNZwang/webapi-hw0/movie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="movies">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="movie" type="movieType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
  </xs:element>
        <xs:complexType name="movieType">
            <xs:sequence>
                <xs:element type="xs:string" name="title">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element type="xs:int" name="year">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:pattern value="\d{4}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element type="xs:string" name="genre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Action"/>
                            <xs:enumeration value="Adventure"/>
                            <xs:enumeration value="Comedy"/>
                            <xs:enumeration value="Crime"/>
                            <xs:enumeration value="Drama"/>
                            <xs:enumeration value="Fantasy"/>
                            <xs:enumeration value="Horror"/>
                            <xs:enumeration value="Mystery"/>
                            <xs:enumeration value="Romance"/>
                            <xs:enumeration value="Thriller"/>
                            <xs:enumeration value="Western"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="actor">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element type="xs:string" name="DateOfBirth">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="(0[1-9]|1[012])[/](0[1-9]|[12][0-9]|3[01])[/](19[0-9][0-9]|20[0-9][0-9])"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
</xs:schema>

=== ZugNZwang/webapi-hw0/movie.xml
<?xml version="1.0"?>
<movies
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="movie.xsd">
    <movie>
        <title>IT</title>
        <year>2017</year>
        <genre>Horror</genre>
        <actor>
            <name>Bill Skarsgard</name>
            <DateOfBirth>08/09/1990</DateOfBirth>
        </actor>
    </movie>
    <movie>
        <title>The Room</title>
        <year>2003</year>
        <genre>Comedy</genre>
        <actor>
            <name>Tommy Wiseau</name>
            <DateOfBirth>10/03/2055</DateOfBirth>
        </actor>
    </movie>
</movies>
